name: deploy to aws-lambda
on:
  push:
    branches:
      - master
      
jobs:
  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1

#       - name: build shadowJar with gradlew
#       - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-15
#         with:
#           args: shadowJar  
        
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build with Gradle
        run: ./gradlew shadowJar       
        
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: border-inn
          zip_file: build/libs/BorderInnDirections.jar
#           memory_size: 128
#           timeout: 10
#           handler: foobar
#           role: arn:aws:iam::xxxxxxxxxxx:role/test1234
#           runtime: nodejs12.x
